# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoJsonschema < Formula
  desc "go-jsonschema binary"
  homepage "https://gihub.com/sighupio/go-jsonschema"
  version "0.15.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sighupio/go-jsonschema/releases/download/v0.15.2/go-jsonschema_Darwin_arm64.tar.gz"
      sha256 "7ac4eae9825680ff81ad160939d277ec2e7f0efebe6e5dc3d8211dd599675c82"

      def install
        bin.install 'go-jsonschema'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sighupio/go-jsonschema/releases/download/v0.15.2/go-jsonschema_Darwin_x86_64.tar.gz"
      sha256 "483d1fbd500b6e8f2c914f1648efcb902d7e2a2eacda7d7b1ca5c95f63a670ce"

      def install
        bin.install 'go-jsonschema'
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sighupio/go-jsonschema/releases/download/v0.15.2/go-jsonschema_Linux_arm64.tar.gz"
      sha256 "cbe1005504f73515b48e3b54f865f33dd3a0d7da19bb35a60ba7d07998411d95"

      def install
        bin.install 'go-jsonschema'
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sighupio/go-jsonschema/releases/download/v0.15.2/go-jsonschema_Linux_x86_64.tar.gz"
      sha256 "3d4ff9f07ea1824fca848965cfa7abecbd56266c824be0189ee97c704579e83d"

      def install
        bin.install 'go-jsonschema'
      end
    end
  end

  test do
    system "#{bin}/go-jsonschema"
  end
end
